---
- name: Configure paths
  set_fact:
    dir_next_version: '{{ dir_versions }}/{{ project_version }}'
    link_current: '{{ dir_env }}/static'

- name: Create version directory
  file:
    path: '{{ dir_next_version }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'

- name: Install rsync
  apt:
    name: rsync
    state: present

- name: Sync files
  synchronize:
    src: '{{ dir_source }}'
    dest: '{{ dir_next_version }}'
    recursive: true

- name: Configure nginx server config file
  template:
    src: nginx-serve-content.conf
    dest: '{{ file_server_config }}'
  notify:
    - reload nginx

- name: Link the deployed version
  file:
    state: link
    src: '{{ dir_next_version }}'
    dest: '{{ link_current }}'
  notify: reload nginx

