---
- name: Configure facts
  set_fact:
    dir_project_environment: '{{nginx_static_projects_directory}}/{{nginx_static_project_name}}/{{nginx_static_project_environment}}'
    dir_project: '{{nginx_static_projects_directory}}/{{nginx_static_project_name}}'
    dir_ssl_certificate: '/etc/letsencrypt/live/{{nginx_static_server_name.split(" ")[0]}}'
    project_config_name: 'static-{{nginx_static_project_name}}-{{nginx_static_project_environment}}'


- name: More facts
  set_fact:
    dir_project_environment_versions: '{{dir_project_environment}}/versions'
    dir_next_version: '{{dir_project_environment}}/versions/{{nginx_static_version}}'
    link_current: '{{dir_project_environment}}/current'
    ssl_certificate_path: '{{dir_ssl_certificate}}/fullchain.pem'
    ssl_certificate_key_path: '{{dir_ssl_certificate}}/privkey.pem'

- include_tasks: deps.yml
- include_tasks: deploy.yml
- include_tasks: config.yml
