---
name: CI
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 19
          docker_channel: stable
      - name: Install docker
        run: sudo apt-get -y install python-docker python3-docker
      - uses: ansible/ansible-lint-action@master
        with:
          targets: |
            defaults/*.yml
            examples/*.yml
            handlers/*.yml
            meta/*.yml
            tasks/*.yml
      - name: Run test deploy
        run: ./uatr/uatr.sh
